[package]
name = "etagere_codegen"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
backend = []
frontend = []

[lib]
proc-macro=true

[dependencies]
convert_case="0.4.0"
proc-macro2="1.0.30"
proc-macro-error="1.0.4"
quote="1.0.9"
syn={version="1.0.78",features=["full"]}
syn-rsx="0.8.0"
regex="1.5.4"

[dev-dependencies]
etagere_view={path="../view", version="*"}