[package]
name = "ahecha-cli"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ahecha]
path="../lib"
version="*"

[dependencies.clap]
version = "3.0"
features = ["cargo"]
