[build]
# The output dir for all final assets.
dist = "./public/dist"
# The public URL from which assets are to be served.
public_url = "/dist/"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["./src"]

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 3001
# Disable auto-reload of the web app.
no_autoreload = true

[clean]
# The output dir for all final assets.
dist = "./public"
