// TODO: Most of the content of this file will be autogenerated
// include!(concat!(env!("OUT_DIR"), "/routes.rs"));

pub mod query;

#[cfg(feature = "rocket")]
use rocket::{routes, Route};

#[cfg(feature = "rocket")]
pub fn routes() -> Vec<Route> {
  routes![query::get]
}
