[package]
name = "ahecha_live_view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahecha_html = { version = "0.0.8", path = "../html" }
axum = { version = "0.4.8", features = ["ws"] }