// TODO: Most of the content of this file will be autogenerated
// include!(concat!(env!("OUT_DIR"), "/routes.rs"));
pub mod index;

use rocket::{routes, Route};

pub fn routes() -> Vec<Route> {
  routes![index::index_page_route]
}
