[package]
name = "ahecha_extra"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahecha_html = { path = "../html", version = "0.0.9" }
ahecha_macro = { path = "../macro", version = "0.0.10", features = ["extra"] }
axum = "0.4.8"

[dev-dependencies]
ahecha = { path = "../lib", version = "0", features = ["partials"] }
async-trait = "0.1.52"
axum-extra = { version = "0.1.5", features = ["typed-routing"] }
serde = { version = "1.0", features = ["derive"] }