[package]
name = "ahecha_extra"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahecha_html = { path = "../html", version = "0.0.9" }
ahecha_macro = { path = "../macro", version = "0.0.10", features = ["extra"] }
axum = "0.4.8"
